"""empty message

Revision ID: ad2aa9a97fe4
Revises: f48ef55b412c
Create Date: 2024-07-05 03:04:39.837764

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad2aa9a97fe4'
down_revision: Union[str, None] = 'f48ef55b412c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login_attempts', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'login_attempts')
    # ### end Alembic commands ###
